name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Docker build and push disabled for now - uncomment when needed
  # build-and-push:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v2
  #   - name: Login to Docker Hub
  #     uses: docker/login-action@v2
  #     with:
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_TOKEN }}
  #   - name: Build and push Docker image
  #     uses: docker/build-push-action@v4
  #     with:
  #       context: .
  #       file: ./Dockerfile
  #       push: ${{ github.event_name != 'pull_request' }}
  #       tags: ${{ secrets.DOCKERHUB_USERNAME }}/savis4-app:${{ github.sha }}
  #       platforms: linux/amd64,linux/arm64

  # Simple job that runs for now - replace with actual deployment steps when needed
  placeholder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Placeholder step
      run: echo "Docker deployment disabled - using Firebase instead"